version: '2'
services:
  webapp:
    container_name: tattva-webapp
    build: .
    image: tattva/tattva-webapp:0.1.0
    network_mode: host
    restart: always
    expose:
      - 8080
    ports:
    - "8080:8080"
    depends_on:
    - mongodb
    - fluentd
    environment:
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DB_NAME: tattva
      REDIS_HOST: localhost
      REDIS_PORT: 6379
  watchloop:
    container_name: tattva-distwatchloop
    build: ./tattva-docker-distwatchloop
    image: tattva/tattva-distwatchloop:0.1.0
    network_mode: host
    restart: always
    expose:
      - 9090
    ports:
    - "9090:9090"
    depends_on:
    - mongodb
    - fluentd
    environment:
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DB_NAME: tattva    
      REDIS_HOST: localhost
      REDIS_PORT: 6379
  mongodb:
    container_name: mongodb
    image: mvertes/alpine-mongo
    network_mode: host
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
 redis:
   container_name: redis
   image: smebberson/alpine-redis
   restart: always
   expose:
     - 6379
   ports:
     - 6379:6379
  fluentd:
    container_name: tattva-git-logger
    image: tattva-git-logger:v1.0.0
    network_mode: host
    restart: always
    expose:
      - 24224
      - 7070
    ports:
      - 24224:24224
      - 7070:7070
