<<<<<<< HEAD
version: '2'
services:
  webapp:
    container_name: tattva-webapp
    build: .
    image: tattva/tattva-webapp:0.1.0
    network_mode: host
    restart: always
    ports:
    - "8080:8080"
    depends_on:
    - mongodb
    environment:
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DB_NAME: tattva
  mongodb:
    container_name: mongodb
    image: mvertes/alpine-mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
=======
version: '2'
services:
  webapp:
    container_name: tattva-webapp
    build: .
    image: tattva/tattva-webapp:0.1.0
    network_mode: host
    restart: always
    expose:
      - 8080
    ports:
    - "8080:8080"
    depends_on:
    - fluentd
    - mongodb
    environment:
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DB_NAME: tattva
  fluentd:
    container_name: tattva-fluentd
    build: ./fluentd-image/
    image: tattva/tattva-fluentd:0.1.0
    network_mode: host
    restart: always
    expose:
      - 24224
    ports:
      - 24224:24224
  mongodb:
    container_name: mongodb
    image: mvertes/alpine-mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
>>>>>>> d0fd2f224528df142a1137002af3700304472817
